### ISSUE TITLE
Admin should allow pasting of judging input/output

### ISSUE THREAD

**Issue by chipbell4** [MercerBinaryBears/Judge#87]

**Comment by ssfinney** [comment]
@chipbell4 Should I make new fields on the model for input and output? Are you wanting to display these things elsewhere in the app, too?

**Comment by chipbell4** [comment]
@ssfinney Nah, I just think we should provide the option in the admin for either uploading judge input/output or just pasting it in. Furthermore, when editing a problem, I'd like for the input/output files to be loaded into the text input as well so we can make tweaks if need be.

**Comment by ssfinney** [comment]
@chipbell4 I just found this again! Is this something I can still knock out for you? I might have a little time over the next few weeks.

**Comment by chipbell4** [comment]
Yeah, I'd love for you to knock this out if you can!

**Comment by chipbell4** [comment]
*Finally* resolved!
